Add dependency on minitest-mock for MT6 compatibility
This prevents test errors with minitest 6+ such as:

~~~
   2) Error:
TestGem2Rpm#test_show_templates:
NoMethodError: undefined method 'stub' for class Gem2Rpm::Distro
    test/test_gem2rpm.rb:40:in 'TestGem2Rpm#test_show_templates'
~~~

This is due to minitest-mock being extracted from Minitest 6+:

https://github.com/minitest/minitest/commit/de9aac1d3f52224ae5d93a186d129c72d5ec979f

This change unfortunately requies Bundler to be used to execute test
suite, because:

1. RubyGems cannot load minitest-mock [[1]]
2. MT6 restrict support to Ruby 3.2+ [[2], [3]]

I wish the use of Bundler can be reverted one day.

[1]: https://github.com/ruby/rubygems/issues/9238
[2]: https://github.com/minitest/minitest-mock/issues/4
[3]: https://github.com/minitest/minitest/issues/1058